# match https://pages.github.com/versions/
os: linux
dist: xenial
addons:
  chrome: stable

language: ruby
cache: bundler
rvm:
  - 2.5.3

install:
  - bundle install # install dependencies
 
before_script:
  - bundle exec jekyll serve &  # start a Web server (use & to start in new process)
  - sleep 3 # give Web server some time to bind to sockets, etc

script:
  - bundle exec rspec spec
  - bundle exec rubocop
