# match https://pages.github.com/versions/
os: linux
env: DISPLAY=':99.0'
dist: xenial
addons:
  chrome: stable

language: ruby
cache: bundler
rvm:
  - 2.5.3
 
before_script:
  - bundle install

script:
  - bundle exec rspec spec
  - bundle exec rubocop
