os: linux
sudo: required
env: DISPLAY=':99.0'
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: ruby
cache: bundler
rvm:
  - 2.4.4
 
before_script:
  - bundle install

script:
  - bundle exec rspec
  - bundle exec rubocop
