# match https://pages.github.com/versions/
os: linux
dist: xenial
addons:
  chrome: stable

language: ruby
cache: bundler

install:
  - bundle install # install dependencies
 
before_script:
  - bundle exec jekyll serve &  # start a Web server (use & to start in new process)
  - sleep 3 # give Web server some time to bind to sockets, etc

matrix:
  # finish build even if rubocop is still running
  fast_finish: true
  include:
    - rvm: 2.5.3
      script:
        - bundle exec rspec
    - rvm: 2.4.4
      script: 
        - bundle exec rubocop
  # allow rubocop to fail
  allow_failures:
    - rvm: 2.4.4
