theme: jekyll-theme-midnight
title: Conor Sheehan

plugins:
  - jekyll-paginate

paginate: 3
paginate_path: "/projects/page:num/"

include:
  - node_modules/@fortawesome/fontawesome-free/svgs/
  - node_modules/@fortawesome/fontawesome-free/css/all.min.cs
  - node_modules/jquery/dist/jquery.min.js
  - node_modules/lightbox2/dist/css/lightbox.min.css
  - node_modules/lightbox2/dist/js/lightbox.min.js
  - node_modules/jstree/dist/jstree.min.js
  - node_modules/jstree/dist/themes/


exclude:
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
  - scripts/*
  - spec/*
  - vendor/*

sass:
  sass_dir: _scss

# https://github.com/github/pages-gem/issues/399
github: [metadata]