theme: jekyll-theme-midnight
title: Conor Sheehan

plugins:
  - jekyll-paginate
  - jekyll-feed

paginate: 5
paginate_path: "/projects/page:num/"

feed:
  tags:
    only:
      - devto

exclude:
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
  - scripts/*
  - spec/*
  - vendor/*

sass:
  sass_dir: _scss

# https://github.com/github/pages-gem/issues/399
github: [metadata]