theme: jekyll-theme-midnight
title: Conor Sheehan
# https://talk.jekyllrb.com/t/error-your-site-could-not-be-built-no-repo-name-found/5688/3
repository: ConorSheehan1/ConorSheehan1.github.io
url: https://conorsheehan1.github.io
baseurl: ""

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-tags
  - jekyll-sitemap

paginate: 5
paginate_path: "/projects/page:num/"

feed:
  tags:
    only:
      - devto

exclude:
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
  - scripts/*
  - spec/*
  - vendor/*
  - dev.md

sass:
  sass_dir: _scss

tag_page_layout: tag_page
tag_page_dir: tag
# required or tag cloud doesn't work
safe: false

# https://github.com/github/pages-gem/issues/399
github: [metadata]
