theme: jekyll-theme-midnight
title: Conor Sheehan

plugins: 
  - jekyll-paginate

paginate: 3
paginate_path: "/projects/page:num/"

exclude: 
  - README.md
  - LICENSE.md
  - Gemfile 
  - Gemfile.lock
  - scripts/*
  - spec/*
  - vendor/*

jstree_theme: "default-dark"

sass:
  sass_dir: _scss

# https://github.com/github/pages-gem/issues/399
github: [metadata]