os: linux
sudo: required
env: DISPLAY=':99.0'
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: ruby
rvm:
  - 2.2.2
 
before_script:
  - sh -e /etc/init.d/xvfb start
