name: ci

on:
  push:
  schedule:
      - cron: '0 0 * * 1' # Every monday at midnight

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install dependencies
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install
    - name: Tests
      run: |
        bundle exec rspec -t ~allow_failure
    - name: Tests allowable failures
      run: |
        bundle exec rspec -t allow_failure
    - name: Lint
      run: |
        bundle exec rubocop
